stations:
  - id: station-energy-store
    name: 储能站
    type: station-energy-store
    enable: true
    logLevel: INFO
    params:
      maxCharge: 30
      maxDischarge: 30
      capacity: 100
    device-children:
      - refId: button-scram
      - refId: led-running
      - refId: led-fault
      - id: ess-1
        name: 储能柜1
        type: energy-store
        driver: ess_pylon_checkwatt
        enable: true
        params:
          maxCharge: 30
          maxDischarge: 30
        device-children:
          - refId: star-charge-100E-1
          - refId: pylon-tech-us108-1
          - refId: button-charge
          - refId: button-discharge

devices:
  - name: Modbus_tcp_5.125
    protocol: modbus_tcp
    enable: true
    logLevel: INFO
    address: 192.168.5.125:502
    timeout: 3000
    device-children:
      - id: pylon-tech-us108-1
        name: 派能MBMS
        enable: true
        driver: bms_pylonTechUs108
        type: bms
        logLevel: INFO
        printCacheValue: false
        params:
          unitId: 2
          syncTime: true # 同步时间
          ratedPower: 100
          capacity: 100
          maxInputPower: 70
          maxOutputPower: 70
  - name: Modbus_rtu_1
    protocol: modbus_rtu
    enable: true
    logLevel: INFO
    address: /dev/ttyRS485-1
    timeout: 3000
    config:
      speed: 9600
      dataBits: 8
      parity: N
      stopBits: 1
    device-children:
      - id: star-charge-100E-1
        name: 阳光电源PCS
        enable: true
        driver: pcs_starCharge100E
        type: pcs
        isMaster: false
        logLevel: INFO
        printCacheValue: false
        params:
          unitId: 1
          ratedPower: 100
          syncTime: false   # 同步时间
  - name: gpio
    protocol: gpio  # sysfs
    enable: true
    logLevel: DEBUG
    params:
      period: 200 # 读取周期
    device-children:
      - id: button-scram
        name: 急停按钮
        enable: true
        level: Error
        params:
          path: /sys/class/gpio/gpio291
          direction: in
      - id: button-charge
        name: 充电开关
        enable: true
        params:
          path: /sys/class/gpio/gpio380
          direction: in
      - id: button-discharge
        name: 放电开关
        enable: true
        params:
          path: /sys/class/gpio/gpio383
          direction: in
          reverse: true
      - id: led-running
        name: 运行指示灯
        enable: true
        params:
          path: /sys/class/gpio/gpio436
          direction: out
      - id: led-fault
        name: 故障指示灯
        enable: true
        params:
          path: /sys/class/gpio/gpio439
          direction: out