database:
  default:
    debug: true

server:
  address: ":15880"
  pprofEnabled: true
  dumpRouterMap: true
  accessLogEnabled: true

logger:
  biz_ems:
    path: "out/logs/biz"
    file: "{Ymd}.log"
    level: "all"
    stdout: true
  biz_device:
    path: "out/logs/biz/device"
    level: "all"
    stdout: true
  biz_protocol:
    path: "out/logs/biz/protocol"
    level: "all"
    stdout: true
  biz_policy:
    path: "out/logs/biz/policy"
    level: "all"
    stdout: true
