

database:
  default:
    debug: false
#    link: "sqlite::@file(data)"
server:
  address: ":80"
  pprofEnabled: false
  dumpRouterMap: false
  accessLogEnabled: false

# 日志组件配置
logger:
  Level:   "INFO"
  biz_ems:
    path: "out/logs/biz"
    file: "{Ymd}.log"
    level: "all"
    stdout: false

# 静态文件配置
static:
  path: "out/static"


