database:
  default:
    debug: true

server:
  address: ":15880"
  pprofEnabled: true
  dumpRouterMap: true
  accessLogEnabled: true

logger:
  biz_ems:
    path: "out/logs/biz"
    file: "{Ymd}.log"
    level: "all"
    stdout: true
