cabinets:
  - CabinetId: 1
    name: 储能柜1
    modbusEnable: false
  - CabinetId : 2
    name: 储能柜2
    modbusEnable: true
    driver: ess_pylon_checkwatt
    params:
      maxCharge: 30
      maxDischarge: 30
devices:
  - name: 485_1
    protocol: modbus_rtu
    enable: false
    logLevel: INFO
    address: /dev/tty.usbserial-AQ03KXVV
    timeout: 30
    config:
      speed: 9600
      dataBits: 8
      parity: N
      stopBits: 1
    device-children:
      - name: ammeter_rtu_example
        enable: false
        unitId: 2
        cabinetId: 1
        driver: ammeter_example
        location: station # 场站级电表
        group: ess
        isMaster: false
        debug: false

  - name: Modbus_tcp
    protocol: modbus_tcp
    enable: true
    logLevel: INFO
    address: 127.0.0.1:1503
    timeout: 3000
    device-children:
      - id: star-charge-100E-1
        name: 阳光电源PCS
        enable: true
        unitId: 1
        cabinetId: 2
        driver: pcs_starCharge100E
        location: cabinet
        group: pcs
        isMaster: false
        logLevel: INFO
        printCacheValue: false
        ratedPower: 100
        syncTime: true   # 同步时间
      - id: pylon-tech-us108-1
        name: 派能MBMS
        enable: true
        unitId: 2
        cabinetId: 2
        driver: bms_pylonTechUs108
        location: cabinet
        group: bms
        isMaster: false
        logLevel: INFO
        printCacheValue: false
        syncTime: true # 同步时间
  - name: gpio
    protocol: gpio  # sysfs
    enable: true
    logLevel: DEBUG
    config:
      period: 200 # 读取周期
    device-children:
      - id: button-scram
        name: 急停按钮
        enable: true
        path: /Users/zhao/Downloads/gpio
        direction: in
        cabinetId: 2 # 不为0代表是柜子上的设备
      - id: button-discharge
        name: 充电开关
        enable: false
        path: /Users/zhao/Downloads/gpio
        direction: in
        cabinetId: 2
      - id: button-discharge
        name: 放电开关
        enable: false
        path: /Users/zhao/Downloads/gpio
        direction: in
        cabinetId: 2
      - id: led-running
        name: 运行指示灯
        enable: false
        path: /Users/zhao/Downloads/gpio
        direction: out
        cabinetId: 2
      - id: led-fault
        name: 故障指示灯
        enable: false
        path: /Users/zhao/Downloads/gpio
        direction: out
        cabinetId: 2