cabinets:
  - id: 1
    name: 储能柜1
    modbusEnable: false
    capacity: 1000

  - id: 2
    name: 储能柜2
    modbusEnable: true
    capacity: 232
devices:
  - name: Modbus_tcp
    protocol: modbus_tcp
    enable: true
    logLevel: INFO
    address: 192.168.5.10:502
    timeout: 3000
    device-children:
      - name: star-charge-100E
        enable: true
        unitId: 1
        cabinetId: 2
        driver: pcs_starCharge100E
        location: cabinet
        group: pcs
        isMaster: false
        logLevel: INFO
        
        ratedPower: 100
      - name: pylon-tech-us108
        enable: true
        unitId: 2
        cabinetId: 2
        driver: bms_pylonTechUs108
        location: cabinet
        group: bms
        isMaster: false
        logLevel: INFO
        