

protocols:
  - id: abc
    protocol: modbus_tcp
    enable: true
    logLevel: INFO
    address: 127.0.0.1:1503
    timeout: 3000
  - id: efg
    protocol: gpio  # sysfs
    enable: true
    logLevel: DEBUG
    address: /Users/zhao/Downloads/gpio
    params:
      exportCommand: "echo %d | %s/export"
      period: 200 # 读取周期
