// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package alarm

import (
	apialarm "application/api/alarm"
)

type ControllerV1 struct{}

func NewV1() apialarm.IAlarmV1 { return &ControllerV1{} }
