// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package protocol

import (
	"application/api/protocol"
)

type ControllerV1 struct{}

func NewV1() protocol.IProtocolV1 {
	return &ControllerV1{}
}
