// Code generated by "stringer -type=AlarmLevel -output=alarm_level_e_string.go"; DO NOT EDIT.

package c_base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ENone-0]
	_ = x[EWarn-1]
	_ = x[EAlarm-2]
	_ = x[EError-3]
}

const _AlarmLevel_name = "ENoneEWarnEAlarmEError"

var _AlarmLevel_index = [...]uint8{0, 5, 10, 16, 22}

func (i AlarmLevel) String() string {
	if i < 0 || i >= AlarmLevel(len(_AlarmLevel_index)-1) {
		return "AlarmLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AlarmLevel_name[_AlarmLevel_index[i]:_AlarmLevel_index[i+1]]
}
