// Code generated by "stringer -type=EConfigFieldsComponentType -trimprefix=EConfigFieldsComponentType -output=c_base_config_fields_component_type_e_string.go"; DO NOT EDIT.

package c_base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EConfigStructFieldsComponentTypeText-0]
	_ = x[EConfigStructFieldsComponentTypeNumber-1]
	_ = x[EConfigStructFieldsComponentTypeSwitch-2]
	_ = x[EConfigStructFieldsComponentTypeSingleSelect-3]
	_ = x[EConfigStructFieldsComponentTypeMultiSelect-4]
	_ = x[EConfigStructFieldsComponentTypeDate-5]
	_ = x[EConfigStructFieldsComponentTypeTime-6]
	_ = x[EConfigStructFieldsComponentTypeDateTime-7]
}

const _EConfigFieldsComponentType_name = "EConfigStructFieldsComponentTypeTextEConfigStructFieldsComponentTypeNumberEConfigStructFieldsComponentTypeSwitchEConfigStructFieldsComponentTypeSingleSelectEConfigStructFieldsComponentTypeMultiSelectEConfigStructFieldsComponentTypeDateEConfigStructFieldsComponentTypeTimeEConfigStructFieldsComponentTypeDateTime"

var _EConfigFieldsComponentType_index = [...]uint16{0, 36, 74, 112, 156, 199, 235, 271, 311}

func (i EConfigFieldsComponentType) String() string {
	if i < 0 || i >= EConfigFieldsComponentType(len(_EConfigFieldsComponentType_index)-1) {
		return "EConfigFieldsComponentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EConfigFieldsComponentType_name[_EConfigFieldsComponentType_index[i]:_EConfigFieldsComponentType_index[i+1]]
}
