// Code generated by "stringer -type=EReadType -trimprefix=R -output=c_base_meta_read_type_e_string.go"; DO NOT EDIT.

package c_base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RBit0-0]
	_ = x[RBit1-1]
	_ = x[RBit2-2]
	_ = x[RBit3-3]
	_ = x[RBit4-4]
	_ = x[RBit5-5]
	_ = x[RBit6-6]
	_ = x[RBit7-7]
	_ = x[RBit8-8]
	_ = x[RBit9-9]
	_ = x[RBit10-10]
	_ = x[RBit11-11]
	_ = x[RBit12-12]
	_ = x[RBit13-13]
	_ = x[RBit14-14]
	_ = x[RBit15-15]
	_ = x[RBcd16-16]
	_ = x[RInt8-17]
	_ = x[RUint8-18]
	_ = x[RInt16-19]
	_ = x[RUint16-20]
	_ = x[RInt32-21]
	_ = x[RUint32-22]
	_ = x[RInt64-23]
	_ = x[RUint64-24]
	_ = x[RFloat32-25]
	_ = x[RFloat64-26]
}

const _EReadType_name = "Bit0Bit1Bit2Bit3Bit4Bit5Bit6Bit7Bit8Bit9Bit10Bit11Bit12Bit13Bit14Bit15Bcd16Int8Uint8Int16Uint16Int32Uint32Int64Uint64Float32Float64"

var _EReadType_index = [...]uint8{0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 45, 50, 55, 60, 65, 70, 75, 79, 84, 89, 95, 100, 106, 111, 117, 124, 131}

func (i EReadType) String() string {
	if i < 0 || i >= EReadType(len(_EReadType_index)-1) {
		return "EReadType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EReadType_name[_EReadType_index[i]:_EReadType_index[i+1]]
}
