// Code generated by "stringer -type=EAlarmLevel -trimprefix=EAlarmLevel -output=c_base_alarm_level_e_string.go"; DO NOT EDIT.

package c_base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EAlarmLevelNone-0]
	_ = x[EAlarmLevelWarn-1]
	_ = x[EAlarmLevelAlarm-2]
	_ = x[EAlarmLevelError-3]
}

const _EAlarmLevel_name = "NoneWarnAlarmError"

var _EAlarmLevel_index = [...]uint8{0, 4, 8, 13, 18}

func (i EAlarmLevel) String() string {
	if i < 0 || i >= EAlarmLevel(len(_EAlarmLevel_index)-1) {
		return "EAlarmLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EAlarmLevel_name[_EAlarmLevel_index[i]:_EAlarmLevel_index[i+1]]
}
