// Code generated by "stringer -type=EAlarmAction -trimprefix=EAlarmAction -output=c_base_alarm_action_e_string.go"; DO NOT EDIT.

package c_base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EAlarmActionLevelUp-0]
	_ = x[EAlarmActionLevelDown-1]
	_ = x[EAlarmActionFirstTrigger-2]
	_ = x[EAlarmActionFirstClear-3]
	_ = x[EAlarmActionNotFirstTrigger-4]
	_ = x[EAlarmActionNotFirstClear-5]
	_ = x[EAlarmActionReset-6]
}

const _EAlarmAction_name = "LevelUpLevelDownFirstTriggerFirstClearNotFirstTriggerNotFirstClearReset"

var _EAlarmAction_index = [...]uint8{0, 7, 16, 28, 38, 53, 66, 71}

func (i EAlarmAction) String() string {
	if i < 0 || i >= EAlarmAction(len(_EAlarmAction_index)-1) {
		return "EAlarmAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EAlarmAction_name[_EAlarmAction_index[i]:_EAlarmAction_index[i+1]]
}
