// Code generated by "stringer -type=ESystemType -trimprefix=S -output=c_base_meta_system_type_e_string.go"; DO NOT EDIT.

package c_base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SUseReadType-0]
	_ = x[SBool-1]
	_ = x[SInt8-2]
	_ = x[SUint8-3]
	_ = x[SInt16-4]
	_ = x[SUint16-5]
	_ = x[SInt32-6]
	_ = x[SUint32-7]
	_ = x[SInt64-8]
	_ = x[SUint64-9]
	_ = x[SFloat32-10]
	_ = x[SFloat64-11]
	_ = x[SString-12]
}

const _ESystemType_name = "UseReadTypeBoolInt8Uint8Int16Uint16Int32Uint32Int64Uint64Float32Float64String"

var _ESystemType_index = [...]uint8{0, 11, 15, 19, 24, 29, 35, 40, 46, 51, 57, 64, 71, 77}

func (i ESystemType) String() string {
	if i < 0 || i >= ESystemType(len(_ESystemType_index)-1) {
		return "ESystemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ESystemType_name[_ESystemType_index[i]:_ESystemType_index[i+1]]
}
