// Code generated by "stringer -type=EConfigStructFieldsComponentType -trimprefix=EConfigStructFieldsComponentType -output=c_base_config_struct_fields_component_type_e_string.go"; DO NOT EDIT.

package c_base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EConfigStructFieldsComponentTypeText-0]
	_ = x[EConfigStructFieldsComponentTypeNumber-1]
	_ = x[EConfigStructFieldsComponentTypeSwitch-2]
	_ = x[EConfigStructFieldsComponentTypeSingleSelect-3]
	_ = x[EConfigStructFieldsComponentTypeMultiSelect-4]
	_ = x[EConfigStructFieldsComponentTypeDate-5]
	_ = x[EConfigStructFieldsComponentTypeTime-6]
	_ = x[EConfigStructFieldsComponentTypeDateTime-7]
}

const _EConfigStructFieldsComponentType_name = "TextNumberSwitchSingleSelectMultiSelectDateTimeDateTime"

var _EConfigStructFieldsComponentType_index = [...]uint8{0, 4, 10, 16, 28, 39, 43, 47, 55}

func (i EConfigStructFieldsComponentType) String() string {
	if i < 0 || i >= EConfigStructFieldsComponentType(len(_EConfigStructFieldsComponentType_index)-1) {
		return "EConfigStructFieldsComponentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EConfigStructFieldsComponentType_name[_EConfigStructFieldsComponentType_index[i]:_EConfigStructFieldsComponentType_index[i+1]]
}
