// Code generated by "stringer -type=EEnergyStoreStatus -output=energy_store_status_e_string.go"; DO NOT EDIT.

package c_base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EPcsStatusUnknown-0]
	_ = x[EPcsStatusOff-1]
	_ = x[EPcsStatusStandby-2]
	_ = x[EPcsStatusCharge-3]
	_ = x[EPcsStatusDischarge-4]
	_ = x[EPcsStatusFault-5]
	_ = x[EPcsStatusSync-6]
}

const _EEnergyStoreStatus_name = "EPcsStatusUnknownEPcsStatusOffEPcsStatusStandbyEPcsStatusChargeEPcsStatusDischargeEPcsStatusFaultEPcsStatusSync"

var _EEnergyStoreStatus_index = [...]uint8{0, 17, 30, 47, 63, 82, 97, 111}

func (i EEnergyStoreStatus) String() string {
	if i < 0 || i >= EEnergyStoreStatus(len(_EEnergyStoreStatus_index)-1) {
		return "EEnergyStoreStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EEnergyStoreStatus_name[_EEnergyStoreStatus_index[i]:_EEnergyStoreStatus_index[i+1]]
}
