package ess_boost_lnxall_v1

import (
	"common/c_base"
	"modbus/p_modbus"
)

var GroupController = &p_modbus.SModbusTask{
	Name:      "GroupController",
	Desc:      "状态控制",
	Addr:      ESS_ON_OFF.Addr,
	Quantity:  ESS_SET_RP_POWER.Addr - ESS_ON_OFF.Addr + 1,
	CycleMill: 1000,
	Lifetime:  c_base.DefaultCacheLifeTime,
	Metas: []*c_base.Meta{
		ESS_ON_OFF, ESS_SET_AP_POWER, ESS_SET_RP_POWER,
	},
}

var GroupDetail = &p_modbus.SModbusTask{
	Name:      "GroupDetail",
	Desc:      "详细信息",
	Addr:      LIMIT_ESS_POWER_ENABLE.Addr,
	Quantity:  ESS_ONLINE_STATUS.Addr - LIMIT_ESS_POWER_ENABLE.Addr + 1,
	CycleMill: 1000,
	Metas: []*c_base.Meta{
		LIMIT_ESS_POWER_ENABLE, ESS_INVERSE_FLOW_ENABLE, ESS_MAX_DEMAND,
		ESS_SYSTEM_STATUS, ESS_INVERSE_WINDOW_POWER,
		ESS_LOAD_POWER, ESS_EXPECTED_POWER, ESS_LC_INPUT_POWER,
		ESS_RATED_POWER, ESS_RATED_CAPACITY, ESS_ALARM_NUM,
		ESS_PROTECT_DISABLE, ESS_PROTECT_ENABLE, ESS_LAST_POWER,
		ESS_MAX_CHARGE_POWER, ESS_MAX_DISCHARGE_POWER, ESS_PV_PERCENT,
		ESS_CHARGE_LIMIT_ENABLE, ESS_DISCHARGE_LIMIT_ENABLE,
		ESS_TARGET_HEAT_TEMP, ESS_TARGET_COOL_TEMP, ESS_CABINET_STATUS,
		ESS_CABINET_PROTECT_DISABLE, ESS_CABINET_PROTECT_ENABLE,
		ESS_CABINET_MAX_CHARGE_POWER, ESS_CABINET_MAX_DISCHARGE_POWER,
		ESS_ONLINE_STATUS,
	},
}
