// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package telemetry

import (
	"application/api/telemetry"
)

type ControllerV1 struct{}

func NewV1() telemetry.ITelemetryV1 {
	return &ControllerV1{}
}
