// Code generated by "stringer -type=EValueType -trimprefix=E -output=c_base_meta_system_type_e_string.go"; DO NOT EDIT.

package c_enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EBool-0]
	_ = x[EInt8-1]
	_ = x[EUint8-2]
	_ = x[EInt16-3]
	_ = x[EUint16-4]
	_ = x[EInt32-5]
	_ = x[EUint32-6]
	_ = x[EInt64-7]
	_ = x[EUint64-8]
	_ = x[EFloat32-9]
	_ = x[EFloat64-10]
	_ = x[EString-11]
}

const _EValueType_name = "BoolInt8Uint8Int16Uint16Int32Uint32Int64Uint64Float32Float64String"

var _EValueType_index = [...]uint8{0, 4, 8, 13, 18, 24, 29, 35, 40, 46, 53, 60, 66}

func (i EValueType) String() string {
	if i < 0 || i >= EValueType(len(_EValueType_index)-1) {
		return "EValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EValueType_name[_EValueType_index[i]:_EValueType_index[i+1]]
}
