// Code generated by "stringer -type=EDeviceRunningStatus -trimprefix=EDeviceRunningStatus -output=c_enum_device_running_status_e_string.go"; DO NOT EDIT.

package c_enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EDeviceRunningStatusRunning-1]
	_ = x[EDeviceRunningStatusStopped-2]
}

const _EDeviceRunningStatus_name = "RunningStopped"

var _EDeviceRunningStatus_index = [...]uint8{0, 7, 14}

func (i EDeviceRunningStatus) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_EDeviceRunningStatus_index)-1 {
		return "EDeviceRunningStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EDeviceRunningStatus_name[_EDeviceRunningStatus_index[idx]:_EDeviceRunningStatus_index[idx+1]]
}
