// Key generated by "stringer -type=EWordOrder -trimprefix=EWordOrder -output=c_enum_word_order_e_string.go"; DO NOT EDIT.

package c_enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WordOrderHighLow-0]
	_ = x[WordOrderLowHigh-1]
}

const _EWordOrder_name = "WordOrderHighLowWordOrderLowHigh"

var _EWordOrder_index = [...]uint8{0, 16, 32}

func (i EWordOrder) String() string {
	if i < 0 || i >= EWordOrder(len(_EWordOrder_index)-1) {
		return "EWordOrder(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EWordOrder_name[_EWordOrder_index[i]:_EWordOrder_index[i+1]]
}
