// Code generated by "stringer -type=EStrategyStatus -trimprefix=EStrategyStatus -output=c_enum_status_e_string.go"; DO NOT EDIT.

package c_enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EStatusEnable-0]
	_ = x[EStatusDisable-1]
	_ = x[EStatusDeleted-2]
}

const _EStrategyStatus_name = "EStatusEnableEStatusDisableEStatusDeleted"

var _EStrategyStatus_index = [...]uint8{0, 13, 27, 41}

func (i EStrategyStatus) String() string {
	if i < 0 || i >= EStrategyStatus(len(_EStrategyStatus_index)-1) {
		return "EStrategyStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EStrategyStatus_name[_EStrategyStatus_index[i]:_EStrategyStatus_index[i+1]]
}
