// Code generated by "stringer -type=EProtocolStatus -trimprefix=EProtocol -output=c_enum_protocol_e_string.go"; DO NOT EDIT.

package c_enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EProtocolDisconnected-0]
	_ = x[EProtocolConnecting-1]
	_ = x[EProtocolConnected-2]
	_ = x[EProtocolMock-3]
}

const _EProtocolStatus_name = "DisconnectedConnectingConnectedMock"

var _EProtocolStatus_index = [...]uint8{0, 12, 22, 31, 35}

func (i EProtocolStatus) String() string {
	if i < 0 || i >= EProtocolStatus(len(_EProtocolStatus_index)-1) {
		return "EProtocolStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EProtocolStatus_name[_EProtocolStatus_index[i]:_EProtocolStatus_index[i+1]]
}
