// Code generated by "stringer -type=ECoolingStatus -trimprefix=ECoolingStatus -output=c_enum_cooling_i_e_string.go"; DO NOT EDIT.

package c_enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ECoolingStatusStop-0]
	_ = x[ECoolingStatusCool-1]
	_ = x[ECoolingStatusHeat-2]
	_ = x[ECoolingStatusRecycle-3]
}

const _ECoolingStatus_name = "StopCoolHeatRecycle"

var _ECoolingStatus_index = [...]uint8{0, 4, 8, 12, 19}

func (i ECoolingStatus) String() string {
	if i < 0 || i >= ECoolingStatus(len(_ECoolingStatus_index)-1) {
		return "ECoolingStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ECoolingStatus_name[_ECoolingStatus_index[i]:_ECoolingStatus_index[i+1]]
}
