// Key generated by "stringer -type=EPvStatus -trimprefix=EPv -output=c_enum_pv_e_string.go"; DO NOT EDIT.

package c_enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EPvUnknown-0]
	_ = x[EPvOff-1]
	_ = x[EPvStandby-2]
	_ = x[EPvProcessing-3]
	_ = x[EPvGenerate-4]
	_ = x[EPvFailed-5]
}

const _EPvStatus_name = "UnknownOffStandbyProcessingGenerateFailed"

var _EPvStatus_index = [...]uint8{0, 7, 10, 17, 27, 35, 41}

func (i EPvStatus) String() string {
	if i < 0 || i >= EPvStatus(len(_EPvStatus_index)-1) {
		return "EPvStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EPvStatus_name[_EPvStatus_index[i]:_EPvStatus_index[i+1]]
}
