// Code generated by "stringer -type=EBmsStatus -trimprefix=EBmsStatus -output=c_enum_bms_e_string.go"; DO NOT EDIT.

package c_enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EBmsStatusUnknown-0]
	_ = x[EBmsStatusOff-1]
	_ = x[EBmsStatusStandby-2]
	_ = x[EBmsStatusCharge-3]
	_ = x[EBmsStatusDischarge-4]
	_ = x[EBmsStatusFault-5]
}

const _EBmsStatus_name = "UnknownOffStandbyChargeDischargeFault"

var _EBmsStatus_index = [...]uint8{0, 7, 10, 17, 23, 32, 37}

func (i EBmsStatus) String() string {
	if i < 0 || i >= EBmsStatus(len(_EBmsStatus_index)-1) {
		return "EBmsStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EBmsStatus_name[_EBmsStatus_index[i]:_EBmsStatus_index[i+1]]
}
