// Code generated by "stringer -type=EGridMode -trimprefix=EGrid -output=c_enum_energy_store_grid_e_string.go"; DO NOT EDIT.

package c_enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EGridUnknown-0]
	_ = x[EGridOn-1]
	_ = x[EGridOff-2]
	_ = x[EGridSync-3]
}

const _EGridMode_name = "UnknownOnOffSync"

var _EGridMode_index = [...]uint8{0, 7, 9, 12, 16}

func (i EGridMode) String() string {
	if i < 0 || i >= EGridMode(len(_EGridMode_index)-1) {
		return "EGridMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EGridMode_name[_EGridMode_index[i]:_EGridMode_index[i+1]]
}
