// Code generated by "stringer -type=EServerState -trimprefix=EState -output=c_enum_server_state_e_string.go"; DO NOT EDIT.

package c_enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EStateInit-0]
	_ = x[EStateRunning-1]
	_ = x[EStateStopped-2]
	_ = x[EStateError-3]
}

const _EServerState_name = "InitRunningStoppedError"

var _EServerState_index = [...]uint8{0, 4, 11, 18, 23}

func (i EServerState) String() string {
	if i < 0 || i >= EServerState(len(_EServerState_index)-1) {
		return "EServerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EServerState_name[_EServerState_index[i]:_EServerState_index[i+1]]
}
