// Code generated by "stringer -type=EDataFormat -trimprefix=DataFormat -output=c_enum_data_format_e_string.go"; DO NOT EDIT.

package c_enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataFormatUInt16-0]
	_ = x[DataFormatInt16-1]
	_ = x[DataFormatUInt32-2]
	_ = x[DataFormatInt32-3]
	_ = x[DataFormatFloat32-4]
	_ = x[DataFormatFloat64-5]
	_ = x[DataFormatBCD-6]
	_ = x[DataFormatBCD32-7]
	_ = x[DataFormatStringASCII-8]
	_ = x[DataFormatStringUTF16-9]
	_ = x[DataFormatBits-10]
	_ = x[DataFormatBitRange-11]
	_ = x[DataFormatCustom-12]
}

const _EDataFormat_name = "UInt16Int16UInt32Int32Float32Float64BCDBCD32StringASCIIStringUTF16BitsBitRangeCustom"

var _EDataFormat_index = [...]uint8{0, 6, 11, 17, 22, 29, 36, 39, 44, 55, 66, 70, 78, 84}

func (i EDataFormat) String() string {
	if i < 0 || i >= EDataFormat(len(_EDataFormat_index)-1) {
		return "EDataFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EDataFormat_name[_EDataFormat_index[i]:_EDataFormat_index[i+1]]
}
