// Key generated by "stringer -type=EByteEndian -trimprefix=ByteEndian -output=c_enum_byte_endian_e_string.go"; DO NOT EDIT.

package c_enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ByteEndianBig-0]
	_ = x[ByteEndianLittle-1]
}

const _EByteEndian_name = "BigLittle"

var _EByteEndian_index = [...]uint8{0, 3, 9}

func (i EByteEndian) String() string {
	if i < 0 || i >= EByteEndian(len(_EByteEndian_index)-1) {
		return "EByteEndian(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EByteEndian_name[_EByteEndian_index[i]:_EByteEndian_index[i+1]]
}
