// Code generated by "stringer -type=EStatus -trimprefix=EStatus -output=c_enum_status_e_string.go"; DO NOT EDIT.

package c_enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EStatusEnable-0]
	_ = x[EStatusDisable-1]
	_ = x[EStatusDeleted-2]
}

const _EStatus_name = "EnableDisableDeleted"

var _EStatus_index = [...]uint8{0, 6, 13, 20}

func (i EStatus) String() string {
	if i < 0 || i >= EStatus(len(_EStatus_index)-1) {
		return "EStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EStatus_name[_EStatus_index[i]:_EStatus_index[i+1]]
}
