// Code generated by "stringer -type=EPriceType -trimprefix=EPriceType -output=c_enum_price_type_e_string.go"; DO NOT EDIT.

package c_enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EPriceTypeValley-1]
	_ = x[EPriceTypePeak-2]
	_ = x[EPriceTypeFlat-3]
	_ = x[EPriceTypeSharp-4]
	_ = x[EPriceTypeDeepValley-5]
}

const _EPriceType_name = "ValleyPeakFlatSharpDeepValley"

var _EPriceType_index = [...]uint8{0, 6, 10, 14, 19, 29}

func (i EPriceType) String() string {
	i -= 1
	if i < 0 || i >= EPriceType(len(_EPriceType_index)-1) {
		return "EPriceType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EPriceType_name[_EPriceType_index[i]:_EPriceType_index[i+1]]
}
