@startuml
namespace c_base {
    class EAlarmLevel << (S,Aquamarine) >> {
        + Name() string
        + FullName() string
        + String() string

    }
    class ECharSequence << (S,Aquamarine) >> {
        + DecodeToString(b []byte) string
        + DecodeToInt(b []byte) int
        + DecodeToUint(b []byte) uint
        + DecodeToBool(b []byte) bool
        + DecodeToInt8(b []byte) int8
        + DecodeToUint8(b []byte) uint8
        + DecodeToInt16(b []byte) int16
        + DecodeToUint16(b []byte) uint16
        + DecodeToInt32(b []byte) int32
        + DecodeToUint32(b []byte) uint32
        + DecodeToInt64(b []byte) int64
        + DecodeToUint64(b []byte) uint64
        + DecodeToFloat32(b []byte) float32
        + DecodeToFloat64(b []byte) float64
        + FillUpSize(b []byte, l int) []byte
        + FillUpSizeBit(b []gbinary.Bit, l int) []gbinary.Bit
        + String() string
        + EncodeString(s string) []byte
        + EncodeInt(i int) []byte
        + EncodeUint(u uint) []byte
        + EncodeBool(b bool) []byte
        + EncodeInt8(i int8) []byte
        + EncodeUint8(u uint8) []byte
        + EncodeInt16(i int16) []byte
        + EncodeUint16(u uint16) []byte
        + EncodeInt32(i int32) []byte
        + EncodeUint32(u uint32) []byte
        + EncodeInt64(i int64) []byte
        + EncodeUint64(u uint64) []byte
        + EncodeFloat32(f float32) []byte
        + EncodeFloat64(f float64) []byte

    }
    class EReadType << (S,Aquamarine) >> {
        + ReadValue(bytes []byte, bitLength uint8, endianness ECharSequence) (any, error)
        + Transform(value any, bitLength uint8, factor float32, offset int) any
        + RegisterSize() uint16
        + Encoder(value int64, factor float32, offset int, endianness ECharSequence) []byte
        + GetReflectKind(bitLength uint8) reflect.Kind

    }
    class ESystemType << (S,Aquamarine) >> {
        + Transform(value any, readType EReadType, bitLength uint8, factor float32, offset int) any
        + GetReflectKind(readType EReadType, bitLength uint8) reflect.Kind

    }
    interface IAlarmHandler  {
        + ClearAlarm() 
        + RegisterAlarmNotify( <font color=blue>chan</font> *SAlarmDetail) 
        + GetAlarmLevel() EAlarmLevel
        + GetAlarmDetails() []*SAlarmDetail
        + HandlerAlarmDetail(alarm *SAlarmDetail) 
        + GetMonitorChan() <font color=blue>chan</font> *SAlarmDetail

    }
    interface IDriver  {
        + GetId() string
        + GetType() EDeviceType
        + GetIsMaster() bool
        + GetName() string
        + GetDescription() SDescription
        + GetCache() *gcache.Cache
        + GetLastUpdateTime() *time.Time
        + Init(ctx context.Context, client IProtocol, cfg any) error
        + IsActivate() bool

    }
    interface IDriverConfig  {
        + GetName() string
        + GetIsMaster() bool
        + GetCabinetId() uint8
        + IsEnable() bool
        + GetGroup() EGroupType

    }
    interface IProtocol  {
        + GetId() string
        + GetType() EDeviceType
        + Init(deviceType EDeviceType) 
        + Close() error
        + IsActivate() bool
        + PrintCacheValues() 
        + GetCache() *gcache.Cache
        + GetLastUpdateTime() *time.Time

    }
    class Meta << (S,Aquamarine) >> {
        + Debug bool
        + Name string
        + Cn string
        + Addr uint16
        + BitLength uint8
        + Endianness ECharSequence
        + ReadType EReadType
        + SystemType ESystemType
        + Level EAlarmLevel
        + Factor float32
        + Offset int
        + Min int64
        + Max int64
        + Precise int
        + Unit string
        + Desc string
        + Trigger <font color=blue>func</font>(any) bool

        + AddrDecString() string
        + GetValueReflectKind() reflect.Kind
        + ValueToString(value *gvar.Var) string

    }
    class SAlarmDetail << (S,Aquamarine) >> {
        + DeviceId string
        + DeviceType EDeviceType
        + Level EAlarmLevel
        + Meta *Meta
        + HappenTime time.Time
        + IsTrigger bool
        + Value any

        + ToString() string

    }
    class SAlarmHandler << (S,Aquamarine) >> {
        + Ctx context.Context

        + ClearAlarm() 
        + GetAlarmLevel() EAlarmLevel
        + RegisterAlarmNotify(details <font color=blue>chan</font> *SAlarmDetail) 
        + GetAlarmDetails() []*SAlarmDetail
        + HandlerAlarmDetail(alarm *SAlarmDetail) 
        + GetMonitorChan() <font color=blue>chan</font> *SAlarmDetail

    }
    class SCabinetConfig << (S,Aquamarine) >> {
        + CabinetId uint8
        + Name string
        + Driver string
        + Enable bool
        + ModbusEnable bool
        + Params <font color=blue>map</font>[string]string

    }
    class SDescription << (S,Aquamarine) >> {
        + Brand string
        + Model string
        + Type EDeviceType
        + Remark string

    }
    class SDriverConfig << (S,Aquamarine) >> {
        + Id string
        + Name string
        + Driver string
        + Group EGroupType
        + CabinetId uint8
        + IsMaster bool
        + Enable bool
        + LogLevel string
        + PrintCacheValue bool
        + Params <font color=blue>map</font>[string]string

        + GetId() string
        + GetName() string
        + GetIsMaster() bool
        + GetCabinetId() uint8
        + IsEnable() bool
        + GetGroup() EGroupType

    }
    class SProtocolConfig << (S,Aquamarine) >> {
        + Name string
        + Protocol EProtocolType
        + Address string
        + Timeout int64
        + LogLevel string
        + Config <font color=blue>map</font>[string]any
        + Enable bool
        + DeviceChildren []<font color=blue>map</font>[string]any

        + GetProtocol() EProtocolType
        + GetAddress() string
        + GetTimeout() int64
        + GetLogLevel() string

    }
    class SSystemConfig << (S,Aquamarine) >> {
        + ConfigPath string
        + DriverPath string
        + ProtocolPath string
        + PrintCacheValueCycle int

        + GetPrintCacheValueCycleDuration() time.Duration

    }
    class c_base.EAlarmLevel << (T, #FF7700) >>  {
    }
    class c_base.ECharSequence << (T, #FF7700) >>  {
    }
    class c_base.EDeviceType << (T, #FF7700) >>  {
    }
    class c_base.EEnergyStoreStatus << (T, #FF7700) >>  {
    }
    class c_base.EGridMode << (T, #FF7700) >>  {
    }
    class c_base.EGroupType << (T, #FF7700) >>  {
    }
    class c_base.EProtocolType << (T, #FF7700) >>  {
    }
    class c_base.EReadType << (T, #FF7700) >>  {
    }
    class c_base.ESystemType << (T, #FF7700) >>  {
    }
}
"c_base.IAlarmHandler" *-- "extends""c_base.IDriver"
"c_base.IAlarmHandler" *-- "extends""c_base.IProtocol"

"c_base.IAlarmHandler" <|-- "implements""c_base.SAlarmHandler"
"c_base.IDriverConfig" <|-- "implements""c_base.SDriverConfig"

namespace c_device {
    interface IAmmeter  {
    }
    interface IAmmeterBasic  {
        + GetPtCt() (float32, float32, error)
        + GetFrequency() (float32, error)
        + GetPowerFactor() (float32, error)
        + GetVoltage() (float32, float32, float32, error)
        + GetCurrent() (float32, float32, float32, error)
        + GetTodayIncomingQuantity() (float64, error)
        + GetHistoryIncomingQuantity() (float64, error)
        + GetTodayOutgoingQuantity() (float64, error)
        + GetHistoryOutgoingQuantity() (float64, error)

    }
    interface IBms  {
    }
    interface IBmsBasic  {
        + SetReset() error
        + SetBmsStatus(status EBmsStatus) error
        + GetBmsStatus() (EBmsStatus, error)
        + GetSoc() (float32, error)
        + GetSoh() (float32, error)
        + GetCellTemp() (float32, float32, float32, error)
        + GetCellVoltage() (float32, float32, float32, error)
        + GetCapacity() (uint16, error)
        + GetCycleCount() (uint, error)
        + GetRatedPower() (int32, error)
        + GetMaxInputPower() (float64, error)
        + GetMaxOutputPower() (float64, error)
        + GetDcPower() (float64, error)
        + GetDcVoltage() (float64, error)
        + GetDcCurrent() (float64, error)
        + GetTodayIncomingQuantity() (float64, error)
        + GetHistoryIncomingQuantity() (float64, error)
        + GetTodayOutgoingQuantity() (float64, error)
        + GetHistoryOutgoingQuantity() (float64, error)

    }
    interface ICharge  {
    }
    interface IChargeBasic  {
        + SetPower(power float64) error
        + SetReactivePower(power float64) error
        + SetPowerFactor(factor float32) error
        + GetTargetPower() float64
        + GetTargetReactivePower() float64
        + GetTargetPowerFactor() float32
        + GetPower() (float64, error)
        + GetApparentPower() (float64, error)
        + GetReactivePower() (float64, error)
        + GetTodayIncomingQuantity() (float64, error)
        + GetHistoryIncomingQuantity() (float64, error)
        + GetTodayOutgoingQuantity() (float64, error)
        + GetHistoryOutgoingQuantity() (float64, error)
        + GetRatedPower() (float64, error)
        + GetMaxInputPower() (float64, error)
        + GetMaxOutputPower() (float64, error)
        + GetCarSoc() (float64, error)

    }
    interface ICoolingAc  {
        + GetCoolingAcStatus() (ECoolingStatus, error)

    }
    interface ICoolingBasic  {
        + SetTemperature(temperature float32) error
        + GetTemperature() (float32, error)
        + GetTargetTemperature() (float32, error)

    }
    interface ICoolingLiquid  {
        + GetLiquidCoolingStatus() (ECoolingStatus, error)
        + GetInputWaterPressure() (float32, error)
        + GetInputWaterTemperature() (float32, error)
        + GetOutputWaterPressure() (float32, error)
        + GetOutputWaterTemperature() (float32, error)

    }
    interface IDriverInstances  {
        + RegisterInstance(info c_base.IDriver) 
        + FindById(id string) c_base.IDriver
        + FindAll() []c_base.IDriver
        + FindByType(t c_base.EDeviceType) []c_base.IDriver
        + RemoveById(id string) 

    }
    interface IEnergyStore  {
    }
    interface IEnergyStoreBasic  {
    }
    interface IFire  {
    }
    interface IFireBasic  {
        + GetFireEnvTemperature() (float64, error)
        + GetCarbonMonoxideConcentration() (float64, error)
        + HasSmoke() (bool, error)

    }
    interface IGenerator  {
    }
    interface IGeneratorBasic  {
        + GetGridFrequency() (float32, error)
        + GetGridVoltage() (float32, float32, float32, error)
        + GetGridCurrent() (float32, float32, float32, error)
        + GetGridPower() (float32, float32, float32, error)
        + SetPower(power float64) error
        + SetReactivePower(power float64) error
        + SetPowerFactor(factor float32) error
        + GetTargetPower() float64
        + GetTargetReactivePower() float64
        + GetTargetPowerFactor() float32
        + GetPower() (float64, error)
        + GetApparentPower() (float64, error)
        + GetReactivePower() (float64, error)
        + GetTodayIncomingQuantity() (float64, error)
        + GetHistoryIncomingQuantity() (float64, error)
        + GetTodayOutgoingQuantity() (float64, error)
        + GetHistoryOutgoingQuantity() (float64, error)
        + GetRatedPower() (float64, error)
        + GetMaxInputPower() (float64, error)
        + GetMaxOutputPower() (float64, error)

    }
    interface IHumiture  {
    }
    interface IHumitureBasic  {
        + GetTemperature() (float64, error)
        + GetHumidity() (float64, error)

    }
    interface IInput  {
        + IsUp() (bool, error)
        + IsDown() (bool, error)

    }
    interface ILoad  {
    }
    interface ILoadBasic  {
        + SetPower(power float64) error
        + SetReactivePower(power float64) error
        + SetPowerFactor(factor float32) error
        + GetTargetPower() float64
        + GetTargetReactivePower() float64
        + GetTargetPowerFactor() float32
        + GetPower() (float64, error)
        + GetApparentPower() (float64, error)
        + GetReactivePower() (float64, error)
        + GetTodayIncomingQuantity() (float64, error)
        + GetHistoryIncomingQuantity() (float64, error)
        + GetTodayOutgoingQuantity() (float64, error)
        + GetHistoryOutgoingQuantity() (float64, error)
        + GetRatedPower() (float64, error)
        + GetMaxInputPower() (float64, error)
        + GetMaxOutputPower() (float64, error)

    }
    interface IOutput  {
        + SetUp() (bool, error)
        + SetDown() (bool, error)

    }
    interface IPcs  {
    }
    interface IPcsBasic  {
        + SetReset() error
        + SetStatus(status c_base.EEnergyStoreStatus) error
        + SetGridMode(mode c_base.EGridMode) error
        + GetStatus() (c_base.EEnergyStoreStatus, error)
        + GetGridMode() (c_base.EGridMode, error)
        + SetPower(power int32) error
        + SetReactivePower(power int32) error
        + SetPowerFactor(factor float32) error
        + GetTargetPower() int32
        + GetTargetReactivePower() int32
        + GetTargetPowerFactor() float32
        + GetPower() (float64, error)
        + GetApparentPower() (float64, error)
        + GetReactivePower() (float64, error)
        + GetRatedPower() (int32, error)
        + GetMaxInputPower() (float64, error)
        + GetMaxOutputPower() (float64, error)
        + GetTodayIncomingQuantity() (float64, error)
        + GetHistoryIncomingQuantity() (float64, error)
        + GetTodayOutgoingQuantity() (float64, error)
        + GetHistoryOutgoingQuantity() (float64, error)

    }
    interface IPv  {
    }
    interface IPvBase  {
        + GetGridFrequency() (float32, error)
        + GetGridVoltage() (float32, float32, float32, error)
        + GetGridCurrent() (float32, float32, float32, error)
        + GetGridPower() (float32, float32, float32, error)
        + SetPower(power float64) error
        + SetReactivePower(power float64) error
        + SetPowerFactor(factor float32) error
        + GetTargetPower() float64
        + GetTargetReactivePower() float64
        + GetTargetPowerFactor() float32
        + GetPower() (float64, error)
        + GetApparentPower() (float64, error)
        + GetReactivePower() (float64, error)
        + GetDcPower() (float64, error)
        + GetDcVoltage() (float64, error)
        + GetDcCurrent() (float64, error)
        + GetTodayIncomingQuantity() (float64, error)
        + GetHistoryIncomingQuantity() (float64, error)
        + GetTodayOutgoingQuantity() (float64, error)
        + GetHistoryOutgoingQuantity() (float64, error)

    }
    class c_device.EBmsStatus << (T, #FF7700) >>  {
    }
    class c_device.ECoolingStatus << (T, #FF7700) >>  {
    }
    class c_device.EInputType << (T, #FF7700) >>  {
    }
    class c_device.EOutputType << (T, #FF7700) >>  {
    }
}
"c_device.IAmmeterBasic" *-- "extends""c_device.IAmmeter"
"c_device.IBmsBasic" *-- "extends""c_device.IBms"
"c_device.ILoadBasic" *-- "extends""c_device.ICharge"
"c_device.IEnergyStoreBasic" *-- "extends""c_device.IEnergyStore"
"c_device.IBmsBasic" *-- "extends""c_device.IEnergyStoreBasic"
"c_device.IFireBasic" *-- "extends""c_device.IEnergyStoreBasic"
"c_device.IPcsBasic" *-- "extends""c_device.IEnergyStoreBasic"
"c_device.IFireBasic" *-- "extends""c_device.IFire"
"c_device.IGeneratorBasic" *-- "extends""c_device.IGenerator"
"c_device.IHumitureBasic" *-- "extends""c_device.IHumiture"
"c_device.ILoadBasic" *-- "extends""c_device.ILoad"
"c_device.IPcsBasic" *-- "extends""c_device.IPcs"
"c_device.IPvBase" *-- "extends""c_device.IPv"


namespace internal_device {
    class sDeviceInstance << (S,Aquamarine) >> {
        + RegisterInstance(info c_base.IDriver) 
        + FindByType(t c_base.EDeviceType) []c_base.IDriver
        + FindById(id string) c_base.IDriver
        + RemoveById(id string) 
        + FindAll() []c_base.IDriver

    }
}

"c_device.IDriverInstances" <|-- "implements""internal_device.sDeviceInstance"

namespace pylon_tech_us108 {
    class PylonTechUs108Bms << (S,Aquamarine) >> {
        + GetDescription() c_base.SDescription
        + Init(ctx context.Context, client c_base.IProtocol, cfg any) error
        + GetType() c_base.EDeviceType
        + HasAlarm() (bool, error)
        + GetRatedPower() (int32, error)
        + GetMaxInputPower() (float64, error)
        + GetMaxOutputPower() (float64, error)
        + SetBmsStatus(status c_device.EBmsStatus) error
        + GetBmsStatus() (c_device.EBmsStatus, error)
        + GetSoc() (float32, error)
        + GetSoh() (float32, error)
        + GetDcPower() (float64, error)
        + GetDcVoltage() (float64, error)
        + GetDcCurrent() (float64, error)
        + GetCellTemp() (float32, float32, float32, error)
        + GetCellVoltage() (float32, float32, float32, error)
        + GetCycleCount() (uint, error)
        + GetTodayIncomingQuantity() (float64, error)
        + GetTodayOutgoingQuantity() (float64, error)
        + GetHistoryIncomingQuantity() (float64, error)
        + GetHistoryOutgoingQuantity() (float64, error)
        + GetCapacity() (uint16, error)
        + SetReset() error
        + _syncTime() error

    }
}
"c_base.IDriverConfig" *-- "extends""pylon_tech_us108.PylonTechUs108Bms"
"p_modbus.IModbusProtocol" *-- "extends""pylon_tech_us108.PylonTechUs108Bms"

"c_device.IBmsBasic" <|-- "implements""pylon_tech_us108.PylonTechUs108Bms"

namespace util {
    interface Number  {
    }
}


namespace util_binary {
    class middleEndian << (S,Aquamarine) >> {
        + String() string
        + GoString() string
        + Uint16(b []byte) uint16
        + PutUint16(b []byte, v uint16) 
        + AppendUint16(b []byte, v uint16) []byte
        + Uint32(b []byte) uint32
        + PutUint32(b []byte, v uint32) 
        + AppendUint32(b []byte, v uint32) []byte
        + Uint64(b []byte) uint64
        + PutUint64(b []byte, v uint64) 
        + AppendUint64(b []byte, v uint64) []byte

    }
    class reverseMiddleEndian << (S,Aquamarine) >> {
        + String() string
        + GoString() string
        + Uint16(b []byte) uint16
        + PutUint16(b []byte, v uint16) 
        + AppendUint16(b []byte, v uint16) []byte
        + Uint32(b []byte) uint32
        + PutUint32(b []byte, v uint32) 
        + AppendUint32(b []byte, v uint32) []byte
        + Uint64(b []byte) uint64
        + PutUint64(b []byte, v uint64) 
        + AppendUint64(b []byte, v uint64) []byte

    }
}


"__builtin__.int" #.. "alias of""c_base.EAlarmLevel"
"__builtin__.int" #.. "alias of""c_base.EEnergyStoreStatus"
"__builtin__.int" #.. "alias of""c_base.EGridMode"
"__builtin__.int" #.. "alias of""c_base.EReadType"
"__builtin__.int" #.. "alias of""c_base.ESystemType"
"__builtin__.int" #.. "alias of""c_device.EBmsStatus"
"__builtin__.int" #.. "alias of""c_device.ECoolingStatus"
"__builtin__.string" #.. "alias of""c_base.EDeviceType"
"__builtin__.string" #.. "alias of""c_base.EGroupType"
"__builtin__.string" #.. "alias of""c_base.EProtocolType"
"__builtin__.string" #.. "alias of""c_device.EInputType"
"__builtin__.string" #.. "alias of""c_device.EOutputType"
"__builtin__.uint8" #.. "alias of""c_base.ECharSequence"
@enduml
