// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package station_ess

import (
	"application/api/station_ess"
)

type ControllerV1 struct{}

func NewV1() station_ess.IStationEssV1 {
	return &ControllerV1{}
}
