// Code generated by "stringer -type=EModbusReadFunction -trimprefix=EMq -output=c_modbus_read_function_e_string.go"; DO NOT EDIT.

package c_modbus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EMqReadCoils-0]
	_ = x[EMqDiscreteInputs-1]
	_ = x[EMqHoldingRegisters-2]
	_ = x[EMqInputRegisters-3]
}

const _EModbusReadFunction_name = "ReadCoilsDiscreteInputsHoldingRegistersInputRegisters"

var _EModbusReadFunction_index = [...]uint8{0, 9, 23, 39, 53}

func (i EModbusReadFunction) String() string {
	if i >= EModbusReadFunction(len(_EModbusReadFunction_index)-1) {
		return "EModbusReadFunction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EModbusReadFunction_name[_EModbusReadFunction_index[i]:_EModbusReadFunction_index[i+1]]
}
