// Code generated by "stringer -type=EAlarmAction -trimprefix=EAlarmAction -output=c_base_alarm_action_e_string.go"; DO NOT EDIT.

package c_base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EAlarmActionEvery-0]
	_ = x[EAlarmActionLevelUp-1]
	_ = x[EAlarmActionLevelDown-2]
	_ = x[EAlarmActionFirstTrigger-3]
	_ = x[EAlarmActionFirstClear-4]
	_ = x[EAlarmActionNotFirstTrigger-5]
	_ = x[EAlarmActionNotFirstClear-6]
	_ = x[EAlarmActionReset-7]
	_ = x[EAlarmActionIgnore-8]
}

const _EAlarmAction_name = "EveryLevelUpLevelDownFirstTriggerFirstClearNotFirstTriggerNotFirstClearResetIgnore"

var _EAlarmAction_index = [...]uint8{0, 5, 12, 21, 33, 43, 58, 71, 76, 82}

func (i EAlarmAction) String() string {
	if i < 0 || i >= EAlarmAction(len(_EAlarmAction_index)-1) {
		return "EAlarmAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EAlarmAction_name[_EAlarmAction_index[i]:_EAlarmAction_index[i+1]]
}
