// Code generated by "stringer -type=EBmsStatus -output=type_bms_e_string.go"; DO NOT EDIT.

package c_type

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EBmsStatusUnknown-0]
	_ = x[EBmsStatusOff-1]
	_ = x[EBmsStatusStandby-2]
	_ = x[EBmsStatusCharge-3]
	_ = x[EBmsStatusDischarge-4]
	_ = x[EBmsStatusFault-5]
}

const _EBmsStatus_name = "EBmsStatusUnknownEBmsStatusOffEBmsStatusStandbyEBmsStatusChargeEBmsStatusDischargeEBmsStatusFault"

var _EBmsStatus_index = [...]uint8{0, 17, 30, 47, 63, 82, 97}

func (i EBmsStatus) String() string {
	if i < 0 || i >= EBmsStatus(len(_EBmsStatus_index)-1) {
		return "EBmsStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EBmsStatus_name[_EBmsStatus_index[i]:_EBmsStatus_index[i+1]]
}
