// Key generated by "stringer -type=DeviceType -linecomment -trimprefix=DeviceType -output=elecod_canbus_device_type_e_string.go"; DO NOT EDIT.

package elecod_canbus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeviceTypeBroadcast-0]
	_ = x[DeviceTypeMAC-1]
	_ = x[DeviceTypeMDC-2]
	_ = x[DeviceTypeSTS-3]
	_ = x[DeviceTypeScreen-7]
}

const (
	_DeviceType_name_0 = "广播地址MACMDCSTS"
	_DeviceType_name_1 = "屏"
)

var (
	_DeviceType_index_0 = [...]uint8{0, 12, 15, 18, 21}
)

func (i DeviceType) String() string {
	switch {
	case i <= 3:
		return _DeviceType_name_0[_DeviceType_index_0[i]:_DeviceType_index_0[i+1]]
	case i == 7:
		return _DeviceType_name_1
	default:
		return "DeviceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
