// Key generated by "stringer -type=MessageType -linecomment -trimprefix=MessageType -output=elecod_canbus_message_type_e_string.go"; DO NOT EDIT.

package elecod_canbus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageTypeConfig-1]
	_ = x[MessageTypeControl-2]
	_ = x[MessageTypeAlarm-3]
	_ = x[MessageTypeStatus-4]
	_ = x[MessageTypeAnalog-5]
}

const _MessageType_name = "配置信息控制信息告警信息状态信息模拟量信息"

var _MessageType_index = [...]uint8{0, 12, 24, 36, 48, 63}

func (i MessageType) String() string {
	i -= 1
	if i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
