// Code generated by "stringer -type=ECharSequence -output=endianness_e_string.go"; DO NOT EDIT.

package c_meta

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EBigEndian-0]
	_ = x[ELittleEndian-1]
	_ = x[EMiddleEndian-2]
	_ = x[EReverseMiddleEndian-3]
}

const _ECharSequence_name = "EBigEndianELittleEndianEMiddleEndianEReverseMiddleEndian"

var _ECharSequence_index = [...]uint8{0, 10, 23, 36, 56}

func (i ECharSequence) String() string {
	if i >= ECharSequence(len(_ECharSequence_index)-1) {
		return "ECharSequence(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ECharSequence_name[_ECharSequence_index[i]:_ECharSequence_index[i+1]]
}
