#!/usr/bin/env bash
set -euo pipefail

# Generate Go bindings using c-for-go

echo "Starting Go bindings generation..."

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CPP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

echo "Script directory: ${SCRIPT_DIR}"
echo "CPP directory: ${CPP_DIR}"

# Check if c-for-go is installed
echo "Checking for c-for-go..."
if ! command -v c-for-go >/dev/null 2>&1; then
  echo "c-for-go not found. Trying to install..."
  go install github.com/xlab/c-for-go@latest
  if [ $? -ne 0 ]; then
    echo "Failed to install c-for-go" >&2
    exit 1
  fi
  echo "c-for-go installed successfully"
fi

# Check if cforgo.yml exists
if [ ! -f "${SCRIPT_DIR}/cforgo.yml" ]; then
  echo "Error: cforgo.yml not found in ${SCRIPT_DIR}" >&2
  exit 1
fi

# Generate bindings
echo "Generating bindings..."
pushd "${SCRIPT_DIR}" >/dev/null
c-for-go -out .. cforgo.yml
if [ $? -ne 0 ]; then
  echo "Failed to generate bindings" >&2
  popd >/dev/null
  exit 1
fi
popd >/dev/null

# Create go.mod file for the generated hexlib module
HEXLIB_DIR="${CPP_DIR}/hexlib"
GO_MOD_FILE="${HEXLIB_DIR}/go.mod"

if [ ! -f "${GO_MOD_FILE}" ]; then
  echo "Creating go.mod file for hexlib module..."
  cat > "${GO_MOD_FILE}" << 'EOF'
module hexlib

go 1.25

// This module contains Go bindings for the hexlib C library
// Generated by c-for-go from hexlib.h
EOF
  echo "Created go.mod file: ${GO_MOD_FILE}"
fi

echo "Bindings generated successfully under @cpp/hexlib"
echo ""
echo "You can now use the generated Go bindings in your project."


