# Generate Go bindings using c-for-go for Windows PowerShell

Write-Host "Starting Go bindings generation..." -ForegroundColor Green

# Get the directory where this script is located
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$CppDir = Split-Path -Parent $ScriptDir

Write-Host "Script directory: $ScriptDir" -ForegroundColor Yellow
Write-Host "CPP directory: $CppDir" -ForegroundColor Yellow

# Check if c-for-go is installed
Write-Host "Checking for c-for-go..." -ForegroundColor Yellow
$cForGoCmd = Get-Command c-for-go -ErrorAction SilentlyContinue

if (-not $cForGoCmd) {
    Write-Host "c-for-go not found in PATH. Trying to install..." -ForegroundColor Yellow
    go install github.com/xlab/c-for-go@latest
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Failed to install c-for-go" -ForegroundColor Red
        exit 1
    }
    Write-Host "c-for-go installed successfully" -ForegroundColor Green
    
    # Try to find it in Go bin directory
    $GoPath = go env GOPATH
    $GoBinPath = Join-Path $GoPath "bin"
    $cForGoExe = Join-Path $GoBinPath "c-for-go.exe"
    
    if (Test-Path $cForGoExe) {
        $cForGoCmd = $cForGoExe
        Write-Host "Found c-for-go at: $cForGoCmd" -ForegroundColor Green
    } else {
        Write-Host "c-for-go still not found after installation" -ForegroundColor Red
        exit 1
    }
} else {
    Write-Host "Found c-for-go in PATH" -ForegroundColor Green
    $cForGoCmd = $cForGoCmd.Source
}

# Check if cforgo.yml exists
$ConfigFile = Join-Path $ScriptDir "cforgo.yml"
if (-not (Test-Path $ConfigFile)) {
    Write-Host "Error: cforgo.yml not found in $ScriptDir" -ForegroundColor Red
    exit 1
}

# Change to the bindings directory
Push-Location $ScriptDir

try {
    # Generate bindings
    Write-Host "Generating bindings..." -ForegroundColor Yellow
    & $cForGoCmd -out .. cforgo.yml
    
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Failed to generate bindings" -ForegroundColor Red
        exit 1
    }
    
    # Create go.mod file for the generated hexlib module
    $HexlibDir = Join-Path $CppDir "hexlib"
    $GoModFile = Join-Path $HexlibDir "go.mod"
    
    if (-not (Test-Path $GoModFile)) {
        Write-Host "Creating go.mod file for hexlib module..." -ForegroundColor Yellow
        $GoModContent = @"
module hexlib

go 1.25

// This module contains Go bindings for the hexlib C library
// Generated by c-for-go from hexlib.h
"@
        $GoModContent | Out-File -FilePath $GoModFile -Encoding UTF8
        Write-Host "Created go.mod file: $GoModFile" -ForegroundColor Green
    }
    
    Write-Host "Bindings generated successfully under @cpp/hexlib" -ForegroundColor Green
    Write-Host ""
    Write-Host "You can now use the generated Go bindings in your project." -ForegroundColor Green
} finally {
    Pop-Location
}
