@echo off
setlocal enabledelayedexpansion

REM Generate Go bindings using c-for-go for Windows

echo Starting Go bindings generation...

REM Get the directory where this script is located
set "SCRIPT_DIR=%~dp0"
set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

REM Get the parent directory (CPP_DIR)
for %%i in ("%SCRIPT_DIR%") do set "CPP_DIR=%%~dpi"
set "CPP_DIR=%CPP_DIR:~0,-1%"

echo Script directory: %SCRIPT_DIR%
echo CPP directory: %CPP_DIR%

REM Check if c-for-go is installed
echo Checking for c-for-go...
where c-for-go >nul 2>&1
if %errorlevel% neq 0 (
    echo c-for-go not found in PATH. Trying to install...
    go install github.com/xlab/c-for-go@latest
    if %errorlevel% neq 0 (
        echo Failed to install c-for-go
        exit /b 1
    )
    echo c-for-go installed successfully
)

REM Try to find c-for-go in Go bin directory
set "GOPATH_BIN="
for /f "tokens=*" %%i in ('go env GOPATH') do set "GOPATH_BIN=%%i\bin"
if exist "%GOPATH_BIN%\c-for-go.exe" (
    set "C_FOR_GO_CMD=%GOPATH_BIN%\c-for-go.exe"
    echo Found c-for-go at: %C_FOR_GO_CMD%
) else (
    set "C_FOR_GO_CMD=c-for-go"
    echo Using c-for-go from PATH
)

REM Change to the bindings directory
pushd "%SCRIPT_DIR%"

REM Check if cforgo.yml exists
if not exist "cforgo.yml" (
    echo Error: cforgo.yml not found in %SCRIPT_DIR%
    popd
    exit /b 1
)

REM Generate bindings
echo Generating bindings...
%C_FOR_GO_CMD% -out .. cforgo.yml
if %errorlevel% neq 0 (
    echo Failed to generate bindings
    popd
    exit /b 1
)

REM Return to original directory
popd

REM Create go.mod file for the generated hexlib module
set "HEXLIB_DIR=%CPP_DIR%\hexlib"
set "GO_MOD_FILE=%HEXLIB_DIR%\go.mod"

if not exist "%GO_MOD_FILE%" (
    echo Creating go.mod file for hexlib module...
    (
        echo module hexlib
        echo.
        echo go 1.25
        echo.
        echo // This module contains Go bindings for the hexlib C library
        echo // Generated by c-for-go from hexlib.h
    ) > "%GO_MOD_FILE%"
    echo Created go.mod file: %GO_MOD_FILE%
)

echo Bindings generated successfully under @cpp/hexlib
echo.
echo You can now use the generated Go bindings in your project.
